import { useNavigate } from 'react-router-dom'

const updates = [
  { id: 1, date: '2026-06-01', title: 'School supplies distributed', desc: 'Distributed notebooks and pens to 20 children in Perambalur.', amount: '₹2,000' },
  { id: 2, date: '2026-05-20', title: 'Tree plantation drive', desc: 'Planted 150 saplings across 3 villages in Tamil Nadu.', amount: '₹1,500' },
]

export default function NGODashboard() {
  const navigate = useNavigate()
  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-green-700 text-white px-6 py-4 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <span className="text-2xl">🌿</span>
          <span className="font-bold text-lg">NGO Transparency</span>
        </div>
        <div className="flex items-center gap-4">
          <span className="text-green-200">NGO Dashboard</span>
          <button onClick={() => navigate('/')} className="bg-green-600 px-4 py-1 rounded-lg hover:bg-green-500 text-sm">Logout</button>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="flex justify-between items-center mb-2">
          <h1 className="text-2xl font-bold text-gray-800">Smile Foundation 🏢</h1>
          <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm font-semibold">✓ Verified NGO</span>
        </div>
        <p className="text-gray-500 mb-8">Manage your campaigns and post fund usage updates.</p>

        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="bg-white rounded-xl p-5 shadow text-center">
            <div className="text-3xl font-bold text-green-600">₹12,00,000</div>
            <div className="text-gray-500 text-sm mt-1">Total Raised</div>
          </div>
          <div className="bg-white rounded-xl p-5 shadow text-center">
            <div className="text-3xl font-bold text-green-600">94</div>
            <div className="text-gray-500 text-sm mt-1">AI Credibility Score</div>
          </div>
          <div className="bg-white rounded-xl p-5 shadow text-center">
            <div className="text-3xl font-bold text-green-600">340</div>
            <div className="text-gray-500 text-sm mt-1">Total Donors</div>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow p-6 mb-8">
          <h2 className="text-lg font-bold text-gray-700 mb-1">AI Credibility Report</h2>
          <p className="text-gray-500 text-sm mb-3">Generated by Claude AI based on your fund usage history</p>
          <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-green-800 text-sm">
            "Smile Foundation has maintained a 94% fund utilization rate over 6 months with verified receipts for all major expenditures. Donors can trust this organization with high confidence. Consistent reporting and transparent communication make this one of the top-rated NGOs on the platform."
          </div>
        </div>

        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-gray-700">Fund Usage Updates</h2>
          <button className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-green-700">
            + Post Update
          </button>
        </div>
        <div className="flex flex-col gap-4">
          {updates.map(u => (
            <div key={u.id} className="bg-white rounded-xl shadow p-5">
              <div className="flex justify-between items-start mb-2">
                <div className="font-bold text-gray-800">{u.title}</div>
                <span className="text-green-600 font-semibold text-sm">{u.amount} spent</span>
              </div>
              <p className="text-gray-600 text-sm mb-2">{u.desc}</p>
              <div className="text-gray-400 text-xs">{u.date}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}